security:
  auth:
    enabled: true
  users:
  - username: admin
    password: admin123
    roles: [ADMIN]
  - username: analyst
    password: analyst123
    roles: [ANALYST]
database:
  url: jdbc:postgresql://postgres:5432/conduktor
  username: conduktor
  password: yourpassword