apiVersion: v1
kind: Service
metadata:
  name: conduktor
spec:
  type: {{ .Values.conduktor.service.type }}
  ports:
    - port: {{ .Values.conduktor.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.conduktor.service.nodePort }}
  selector:
    app: conduktor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduktor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduktor
  template:
    metadata:
      labels:
        app: conduktor
    spec:
      {{- $platformSecretName := default "platform-secrets" .Values.platformSecrets.existingSecret }}
      containers:
        - name: conduktor
          image: {{ .Values.conduktor.image.repository }}:{{ .Values.conduktor.image.tag }}
          imagePullPolicy: {{ .Values.conduktor.image.pullPolicy }}
          env:
            - name: CDK_ADMIN_EMAIL
              value: {{ .Values.conduktor.adminEmail | quote }}
            - name: CDK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $platformSecretName }}
                  key: cdk-admin-password
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-conduktor:5432/conduktor"
            - name: DATABASE_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $platformSecretName }}
                  key: postgres-password
            - name: DATABASE_TYPE
              value: "postgresql"
            - name: CONDUKTOR_CONFIG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $platformSecretName }}
                  key: postgres-password
            - name: CONDUKTOR_ANALYST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $platformSecretName }}
                  key: conduktor-analyst-password
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: conduktor-config
              mountPath: /opt/conduktor/default-platform-config.yaml
              subPath: default-platform-config.yaml
      volumes:
        - name: conduktor-config
          configMap:
            name: conduktor-config
