{{- if not .Values.platformSecrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  postgres-password: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | quote }}
  cdk-admin-password: {{ required "conduktor.adminPassword is required" .Values.conduktor.adminPassword | quote }}
  conduktor-analyst-password: {{ required "conduktor.analystPassword is required" .Values.conduktor.analystPassword | quote }}
{{- end }}
