apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  postgres-password: admin
  arango-root-password: admin
  cdk-admin-password: admin
  conduktor-analyst-password: admin