# The Following is required to allow Spark to be able to manage Driver and Executor pods
# Make sure namespace `ksoot` is already created.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: ksoot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: ksoot
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: ksoot
subjects:
- kind: ServiceAccount
  name: spark
  namespace: ksoot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role