database:
  type: postgresql
  host: postgres-conduktor
  port: 5432
  name: conduktor
  username: postgres
  password: ${DATABASE_PASSWORD}
  ssl: false
  userManagement:
    enabled: true
  authentication:
    method: database
security:
  auth:
    enabled: true
  users:
  - username: admin
    password: ${CDK_ADMIN_PASSWORD}
    roles: [ADMIN]
  - username: analyst
    password: ${CDK_ANALYST_PASSWORD}
    roles: [ANALYST]