# Environment-specific values for DEV
conduktor:
  adminEmail: dev-admin@company.com
  adminPassword: ""
  analystPassword: ""
  service:
    nodePort: 30081
postgresql:
  auth:
    password: ""
image:
  tag: dev