# Environment-specific values for STG
conduktor:
  adminEmail: stg-admin@company.com
  adminPassword: ""
  analystPassword: ""
  service:
    nodePort: 30083
postgresql:
  auth:
    password: ""
image:
  tag: stg