# Environment-specific values for PRD
conduktor:
  adminEmail: prd-admin@company.com
  adminPassword: ""
  analystPassword: ""
  service:
    nodePort: 30084
postgresql:
  auth:
    password: ""
image:
  tag: prd